// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResticManager.Testing.Data;

#nullable disable

namespace ResticManager.Testing.Migrations
{
    [DbContext(typeof(ResticContext))]
    [Migration("20231125174445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ResticManager.Testing.Data.ResticRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CompressionRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("CompressionSpaceSaving")
                        .HasColumnType("REAL");

                    b.Property<double>("DeduplicationRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KeyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SnapshotCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalBlobCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCompressedSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalOriginSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalUncompressedSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("ResticManager.Testing.Data.ResticSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CompressionRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("CompressionSpaceSaving")
                        .HasColumnType("REAL");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalBlobCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCompressedSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalOriginSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalUncompressedSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ResticSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
